version: 2.1
orbs:
  python: circleci/python@2.0.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
    - checkout
    - run: pip install cfn-lint
    - run:
        name: run cfn-lint
        command: |
          cfn-lint -i W3002 -t cfn_template/*.yml
  build:
    executor: ansible-playbook/default        
    steps: 
    - checkout
    - add_ssh_keys:
          fingerprints:
            - a2:e0:f6:29:6a:0d:4a:9e:1c:45:f6:78:b5:2d:17:3c
    - ansible-playbook/install:
        version: 2.9.23   
    - ansible-playbook/playbook: 
        playbook: ansible/playbook.yml
        playbook-options: "-i ansible/inventory"
        
  test:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps: 
          app-dir: serverspec
      - run: |
          cd serverspec
          bundle exec rake spec     
workflows:
  raisetech:
    jobs:
    - cfn-lint
    - build
    - test:
        requires:
        - build
